-- MySQL Script generated by MySQL Workbench
-- qua 20 mai 2020 18:14:07 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema helpdesk
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `helpdesk` ;

-- -----------------------------------------------------
-- Schema helpdesk
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `helpdesk` DEFAULT CHARACTER SET utf8mb4 ;
USE `helpdesk` ;

-- -----------------------------------------------------
-- Table `helpdesk`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helpdesk`.`categorias` ;

CREATE TABLE IF NOT EXISTS `helpdesk`.`categorias` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `hidden` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `helpdesk`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helpdesk`.`clientes` ;

CREATE TABLE IF NOT EXISTS `helpdesk`.`clientes` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `usuario` int(11) NOT NULL,
    `nome` varchar(250) NOT NULL,
    `logradouro` varchar(250) NOT NULL,
    `complemento` varchar(250) NOT NULL,
    `bairro` varchar(250) NOT NULL,
    `cidade` varchar(250) NOT NULL,
    `estado` varchar(250) NOT NULL,
    `ierg` varchar(250) NOT NULL,
    `cpfcnpj` varchar(250) NOT NULL,
    `obs` text NOT NULL,
    `criado` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `alterado` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `helpdesk`.`prioridades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helpdesk`.`prioridades` ;

CREATE TABLE IF NOT EXISTS `helpdesk`.`prioridades` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `hidden` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `helpdesk`.`servicos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helpdesk`.`servicos` ;

CREATE TABLE IF NOT EXISTS `helpdesk`.`servicos` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `hidden` INT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `helpdesk`.`tickets`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helpdesk`.`tickets` ;

CREATE TABLE IF NOT EXISTS `helpdesk`.`tickets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` INT(11) NOT NULL,
  `assunto` VARCHAR(250) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `servico` INT(11) NOT NULL,
  `categoria` INT(11) NOT NULL,
  `prioridade` INT(11) NOT NULL,
  `criado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  `ultima_resposta` DATETIME NULL DEFAULT NULL,
  `lido_usuario` DATETIME NULL DEFAULT NULL,
  `lido_admin` DATETIME NULL DEFAULT NULL,
  `resolvido` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tickets_servicos_idx` (`servico` ASC) VISIBLE,
  INDEX `fk_tickets_categorias1_idx` (`categoria` ASC) VISIBLE,
  INDEX `fk_tickets_prioridades1_idx` (`prioridade` ASC) VISIBLE,
  CONSTRAINT `fk_tickets_servicos`
    FOREIGN KEY (`servico`)
    REFERENCES `helpdesk`.`servicos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `helpdesk`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tickets_prioridades1`
    FOREIGN KEY (`prioridade`)
    REFERENCES `helpdesk`.`prioridades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `helpdesk`.`respostas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `helpdesk`.`respostas` ;

CREATE TABLE IF NOT EXISTS `helpdesk`.`respostas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` INT(11) NOT NULL,
  `mensagem` TEXT NOT NULL,
  `ticket` INT(11) NOT NULL,
  `criado` DATETIME NULL DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id`),
  INDEX `fk_respostas_tickets1_idx` (`ticket` ASC) VISIBLE,
  CONSTRAINT `fk_respostas_tickets1`
    FOREIGN KEY (`ticket`)
    REFERENCES `helpdesk`.`tickets` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

